# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-tree" do
  name "git-tree"
  desc "Visualize a git repository’s commit history as an interactive graph."
  homepage "https://github.com/anton-dovnar/git-tree"
  version "0.1.4"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-tree"

  on_macos do
    on_intel do
      url "https://github.com/anton-dovnar/git-tree/releases/download/v#{version}/git-tree_Darwin_x86_64.zip",
        verified: "github.com/anton-dovnar/git-tree"
      sha256 "35c93ff2d27e460c160befe32308b5d4692aa8ee639b8474a094ea9477d0be90"
    end
    on_arm do
      url "https://github.com/anton-dovnar/git-tree/releases/download/v#{version}/git-tree_Darwin_arm64.zip",
        verified: "github.com/anton-dovnar/git-tree"
      sha256 "c8885db43a13d835e1587c2fc9970d08223dd656f799c8349e13c1a1079f3223"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-tree"]
    end
  end

  # No zap stanza required
end
