# This file was generated by GoReleaser. DO NOT EDIT.
cask "git-tree" do
  name "git-tree"
  desc "Visualize a git repository’s commit history as an interactive graph."
  homepage "https://github.com/anton-dovnar/git-tree"
  version "0.1.3"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "git-tree"

  on_macos do
    on_intel do
      url "https://github.com/anton-dovnar/git-tree/releases/download/v#{version}/git-tree_Darwin_x86_64.zip",
        verified: "github.com/anton-dovnar/git-tree"
      sha256 "65b5d4153f17eeb0b4f57647852213ae2ba7284e2a753efe7ec3a0b29b7b6cbd"
    end
    on_arm do
      url "https://github.com/anton-dovnar/git-tree/releases/download/v#{version}/git-tree_Darwin_arm64.zip",
        verified: "github.com/anton-dovnar/git-tree"
      sha256 "8e19676645e399429e5b97ed5c069e16b15f42f8642c6192e0555a781e3dc54a"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/git-tree"]
    end
  end

  # No zap stanza required
end
